### ISSUE TITLE
leaking arguments

### ISSUE THREAD

**Issue by iamstarkov** [andrepolischuk/numd#5]
Leaking arguments are bad for performance. Maybe it’s time for Rest operator from ES6?

https://github.com/andrepolischuk/numd/blob/master/index.js#L18
https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments
https://github.com/lukehoban/es6features#default--rest--spread

**Comment by andrepolischuk** [comment]
But rest is compiled into arguments if we use module in es5?

**Comment by iamstarkov** [comment]
yep, but it compiles in non-leaking way (I hope).

**Comment by iamstarkov** [comment]
I tried it today, and it not leaking =) the thing is not about arguments itself, but about using arguments this way: `[].slice.call(arguments);`
