### ISSUE TITLE
less responsibility is more flexibility

### ISSUE THREAD

**Issue by iamstarkov** [andrepolischuk/numd#6]
for jsunderhood.ru header, I already use numd for pluralizing, but I also want to use [typographic-numbers](https://github.com/andrepolischuk/typographic-numbers), but it seems to be impossible, because numd consume `number` and simple string with it this number inside.

Is it possible for `numd` to become more flexible and to return only one of plural form. Usage will look like this:

```js
import numd from 'numd';
import numbers from 'typographic-numbers';

const fellas = 1455;
const plural = numd('человек', 'человека', 'людей');

// this is doable now
const simple = `${fellas} ${plural(fellas)}`;  // 1455 человек

// this is not, but desired
const adv = `${numbers(fellas)} ${plural(fellas)}`;  // 1 455 человек
```

**Comment by andrepolischuk** [comment]
Actually, typographic-numbers parses `string`, so you can use:

```js
const adv = `${numbers(plural(fellas))}`; // 1 455 человек
```

**Comment by iamstarkov** [comment]
completely forgot about parsing string, thank you

**Comment by andrepolischuk** [comment]
=)

**Comment by andrepolischuk** [comment]
Can I close this?

**Comment by iamstarkov** [comment]
sure

**Comment by iamstarkov** [comment]
here we go https://github.com/iamstarkov/jsunderhood/commit/17ee4716c20a86e4108df46f4d781fe8ec724c96
